ensemble_monday/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("daemun.urls")),
    #path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    #path("polls/", include("polls.urls")),
    path("faq/", include("faq.urls")),
    path("team/", include("team.urls")),
    path("gadmin/", include("gsheets.urls")),
    path("updates/", include("myupdates.urls")),
    #path("updates/", include("updates.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from django.conf.urls import include
from faq import views

urlpatterns = [path('', views.faq, name = 'faq')]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
        # ex: /polls/
        path('', views.index, name = 'polls_index'),
        # ex: /polls/5
        path('<int:question_id>/', views.detail, name = 'polls_detail'),
        # ex: /polls/5/results/
        path('<int:question_id>/results', views.results, name = 'polls_results'),
        # ex: /polls/5/results/vote/
        path('<int:question_id>/vote', views.vote, name = 'polls_votes'),
        ]

ensemble_monday/templates/archive.html
<!--***** Photo Slide *****-->

<!--<style>
.container { 
    display: flex; 
    overflow-x: auto;
}
.container img{
    margin-right: 15px;
}
 
</style>-->


<!--<tr valign = "top">
    <td colspam = "5">
        <h3> Anam Restaurant Week 3.0  </h3>
    </td>
</tr>-->

<!--<div class = "container">
    <img src = "/media/page/images/1.jpeg" alt = "GroupPic" width = "400", height = "auto">
    <img src = "/media/page/images/2.jpeg" alt = "GroupPic" width = "400", height = "auto">
    <img src = "/media/page/{{page.page_images}}" alt = "GroupPic" width = "400", height = "auto">
</div>

<tr valign="top">
    <td colspan="5">
        <div class="button-container" align="center" style="padding: 10 10 10 10px;">
            <a href="https://bit.ly/2SinxOO" target="_blank" style="-webkit-text-size-adjust: none; text-decoration: none; display: inline-block; color: #ffffff; background-color: #000000; border-radius: 0px; -webkit-border-radius: 0px; -moz-border-radius: 0px; width: auto; width: auto; border-top: 1px solid #000000; border-right: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000;padding: 15px; padding-bottom: 15px; font-family:sans-serif, serif, Georgia, Times, Times New Roman; text-align: center; mso-border-alt: none; word-break: keep-all;"><span style="padding-left:40px;padding-right:40px;font-size:18px;display:inline-block;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;"><span style="font-size: 18px; line-height: 36px;" data-mce-style="font-size: 18px; line-height: 36px;"><strong>지금 참여하기</strong></span></span></span></a>
        </div>
    </td>
</tr>-->


<!--***** Header ver1.0 *****-->


<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'daemun' %}"> Ensemble 2.0</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class= "nav-item active">
                <a class= "nav-link" href="{% url 'daemun' %}">Home</a>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog_index' %}"> 9/7 - 9/25 </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'polls:polls_index' %}">Polls</a>
            </li>
          </ul>
        </div>
    </div>
</nav>-->


    <!--***** Comments.view *****-->


<!-- Archives
#def blog_detail(request, pk):
#    post = Post.objects.get(pk=pk)

    #form = CommentForm()
    #if request.method == "POST":
    #   form = CommentForm(request.POST)
    #   if form.is_valid():
    #       comment = Comment(
    #               author=form.cleaned_data["author"],
    #               body=form.cleaned_data["body"],
    #               post=post,
    #               )
    #       comment.save()
    #       return redirect("/blog/")
       #edit url to redirect
    #comments = Comment.objects.filter(post=post)
    #context = {"post":post, "comments":comments, "form":form,}
    #return render(request, "blog_detail.html", context)

#def blog_detail(request, pk):
#    post = Post.objects.get(pk=pk)

    #form = CommentForm()
    #if request.method == "POST":
    #   form = CommentForm(request.POST)
    #   if form.is_valid():
    #       comment = Comment(
    #               author=form.cleaned_data["author"],
    #               body=form.cleaned_data["body"],
    #               post=post,
    #               )
    #       comment.save()
    #       return redirect("/blog/")
       #edit url to redirect
    #comments = Comment.objects.filter(post=post)
    #context = {"post":post, "comments":comments, "form":form,}
    #return render(request, "blog_detail.html", context)-->


    <!--***** Blog Index Ver1.0 *****-->


<!--<div class="col-md-8 offset-md-2">
    <h3>Restaurant Week</h3>
    <hr>
    {% for post in posts %}
    <h3><a href="{% url 'blog_detail' post.pk%}">{{post.title}}</a></h3>
    <small>
        {{ post.created_on.date}} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a> |&nbsp;
        {% endfor %}
        <a> 총펀딩액: {{ post.totalfund  }}</a> 
    </small>
    
    <div class = "progress" style = "height:15px; width:340px;" valign = "top;" >
        <div class = "progress-bar" role = "progressbar" style = "width: {{post.call_rate}}%;"  aria-valuemin = "0" aria-valuemax = "100"> {{post.call}}%(총 25만 8천원)</div>
    </div>

    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>-->

ensemble_monday/templates/base.html
{% load static %}

<html lang="en" class="fontawesome-i2svg-active fontawesome-i2svg-complete">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Ensemble 2.0</title>
        
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico'  %}" />
        
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
       
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />


    </head>

    {% include 'header.html' %}     

<body>
    <!-- Two new div containers -->
    <div id="wrapper">
    {% block page_content %}
    {% endblock %}
    <div id="push">
    </div>
    </div>
</body>
    

    <!-- Adding Styles-->
    <style>
    html, body{
        height: 100%;
        margin: 0;
    }
    
    #wrapper{
        min-height: 100%;
        margin-bottom: -60px;
    }

    #footer,
    #push{
        height: 60px;
    }
    </style>
    

    {% include 'footer.html' %} 
 
        <!-- Bootstrap core JS-->
        <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>       

        <!-- Third party plugin JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
   
        <!-- Tests -->

 
        
    
        
</html>

ensemble_monday/templates/footer.html
<footer class="bg-light py-5">
    <div class="container">
        <div class="small text-center text-muted"> Powered by Ensemble 
        </div>
        <div>
        <center><div> <img src="https://i.imgur.com/cpPsam1.png" style="width: 45px; height: auto;" /> </div></center>
        </div>
    </div>
</footer>

<!-- Bootstrap core JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<!-- Third party plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>

ensemble_monday/templates/header.html
{% load static %}

<body id = "page-top" style= "padding-top: 55px;">

    <!-- Navigation 3 -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-2" style="background-color: white; font-family: Merriweather Sans, 'Noto Sans KR', sans-serif; box-shadow: 0 0.2rem 1rem rgba(0, 0, 0, 0.12); font-weight: 700;">
    <div class = "container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'daemun' %}"> Ensemble 2.0 </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto my-2 my-lg-0">
      <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'daemun' %}"> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'blog_index' %}">Restaurants</a>
      </li>
      <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'faq' %}">FAQ</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle js-stroll-trigger" href="{% url 'team' %}" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ensemble
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'team' %}">Team</a>
            <a class="dropdown-item" href="{% url 'press' %}">Press & Media</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

</body>

</body>