ensemble_monday/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("", include("daemun.urls")),
    #path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    #path("polls/", include("polls.urls")),
    path("faq/", include("faq.urls")),
    path("team/", include("team.urls")),
    path("gadmin/", include("gsheets.urls")),
    path("updates/", include("myupdates.urls")),
    #path("updates/", include("updates.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from django.conf.urls import include
from faq import views

urlpatterns = [path('', views.faq, name = 'faq')]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
        # ex: /polls/
        path('', views.index, name = 'polls_index'),
        # ex: /polls/5
        path('<int:question_id>/', views.detail, name = 'polls_detail'),
        # ex: /polls/5/results/
        path('<int:question_id>/results', views.results, name = 'polls_results'),
        # ex: /polls/5/results/vote/
        path('<int:question_id>/vote', views.vote, name = 'polls_votes'),
        ]

polls/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta, date, time

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
# Create your models here.

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from django.template import loader
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls_index.html')
    context = { 'latest_question_list': latest_question_list, }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls_detail.html", {'question':question})
    #return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls_results.html', {'question': question})
 
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
    # Redisplay the question voting form.
        return render(request, 'polls_detail.html', {
        'question': question,
        'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedircet after succesfully dealing with POST data. This prevents data from wbeing posted twice if a user hits the back button.
        return HttpResponseRedirect(reverse('polls:polls_results', args = (question.id,)))

# Create your views here.

polls/templates/polls_detail.html
{% extends "base.html" %}

{% block page_content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>{{ question.question_text }}</h1>

<form action = "{% url 'polls:polls_votes' question.id %}" method = "post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id  }}">
    <label for = "choice{{ forloop.counter }}">{{ choice.choice_text  }}</label>
<br>
{% endfor %}
<input type = "submit" value = "Vote">
</form>



{% endblock %}

polls/templates/polls_index.html
{% extends "base.html" %}

{% block page_content %}

<div class = "col-md-8 offset-md-2">
    <h3>Live Polls</h3>
    <hr>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:polls_detail' question.id%}">{{ question.question_text }}</a>
</li>
    {% endfor %}
    </ul>
{% else %}
    <p> No polls are available.</p>
{% endif %}
</div>
{% endblock %}

polls/templates/polls_results.html
{% extends "base.html" %}

{% block page_content %}

<h1>{{ question.question_text  }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text  }} -- {{ choice.votes  }} vote{{ choice.votes | pluralize  }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:polls_detail' question.id %}">Vote again?</a>

{% endblock %}